name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Black check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          version: "22.6.0"
